apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: nginx-http
      protocol: TCP
    selector:
        app: nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: nginx-http
          containerPort: 80
